#PBS -S /bin/bash

# 2014-09-26 DSP - Example batch job script for a parallel OpenFOAM run on Parallel or Lattice

cd $PBS_O_WORKDIR
echo "Current working directory is `pwd`"

# Set up the environment

# If using a custom application, define a directory similar to this:
#export FOAM_USER_APPBIN=/global/scratch/phillips/software/openfoam/bin

echo "Working in $PWD"

echo "Node file: $PBS_NODEFILE :"
echo "---------------------"
cat $PBS_NODEFILE
echo "---------------------"


echo "Using mpirun: `which mpirun`"
FOAM=`which pisoFoam`
echo "About to run $FOAM at `date`"
#mpiexec pisoFoam -parallel  > pisoFoam_${PBS_JOBID}.out
mpiexec --mca mpi_warn_on_fork 0 -n 96 pisoFoam -parallel > pisoFoam_DES_zeroValidation_96_${PBS_JOBID}.out
echo "Finished at `date`"
